import type { Metadata } from 'next';
import { Inder } from 'next/font/google';
import { Header } from '@/components/Header';
import { LanguageProvider } from '@/contexts/intlContext';
import './globals.css';

const inder = Inder({ subsets: ['latin'], weight: ['400'], style: 'normal' });

export const metadata: Metadata = {
  title: 'Matryca losu',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inder.className}>
        <LanguageProvider>
          <Header />
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
